create sequence IF NOT EXISTS hibernate_sequence start with 1 increment by 1;
create TABLE IF NOT EXISTS doctor (
id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
uuid VARCHAR(255) NOT NULL,
full_name VARCHAR(255) NOT NULL,
id_specialization integer NOT NULL,
CONSTRAINT pk_doctor PRIMARY KEY (id)
);

create TABLE IF NOT EXISTS specialization(
id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(123) NOT NULL,
CONSTRAINT pk_specialization PRIMARY KEY (id)
);

create TABLE IF NOT EXISTS doctor_specialization(
id_doctor integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
id_specialization VARCHAR(123) NOT NULL,
CONSTRAINT pk_doctor_specialization PRIMARY KEY (id_doctor,id_specialization)
);

create TABLE IF NOT EXISTS client (
id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
uuid VARCHAR(255) NOT NULL,
full_name VARCHAR(255) NOT NULL,
birth_date timestamptz NOT NULL,
CONSTRAINT pk_client PRIMARY KEY (id)
);

create TABLE IF NOT EXISTS ticket (
id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
id_doctor VARCHAR(255) NOT NULL,
id_client VARCHAR(255) NOT NULL,
start_time timestamptz NOT NULL,
CONSTRAINT pk_ticket PRIMARY KEY (id)
);


