//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.08 at 01:43:26 AM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package schedule1.localhost._8080;
